"""empty message

Revision ID: 1e70400de880
Revises: 210813625b76
Create Date: 2024-07-17 23:12:24.555802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e70400de880'
down_revision = '210813625b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_workout', schema=None) as batch_op:
        batch_op.alter_column('week_start',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_workout', schema=None) as batch_op:
        batch_op.alter_column('week_start',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
